services:
  postgram-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.database:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
